# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='src/sto/core/networking/protocolbuffers/Consts.proto',
  package='Sto.Network',
  serialized_pb='\n4src/sto/core/networking/protocolbuffers/Consts.proto\x12\x0bSto.Network*3\n\x0bMessageType\x12\x0f\n\x0bMSG_INVALID\x10\x00\x12\x13\n\x0eMSG_STO_SERVER\x10\x90N')

_MESSAGETYPE = descriptor.EnumDescriptor(
  name='MessageType',
  full_name='Sto.Network.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MSG_INVALID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSG_STO_SERVER', index=1, number=10000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=69,
  serialized_end=120,
)


MSG_INVALID = 0
MSG_STO_SERVER = 10000



# @@protoc_insertion_point(module_scope)
