# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='src/sto/core/networking/protocolbuffers/Sto.proto',
  package='Sto.Network',
  serialized_pb='\n1src/sto/core/networking/protocolbuffers/Sto.proto\x12\x0bSto.Network\"\x1d\n\rConnectServer\x12\x0c\n\x04hash\x18\x01 \x02(\t\"L\n\x15\x43onnectServerResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\r\",\n\nDisconnect\x12\r\n\x05title\x18\x01 \x02(\t\x12\x0f\n\x07message\x18\x02 \x02(\t\"p\n\nServerInfo\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\x14\n\x0cplayer_count\x18\x03 \x02(\x05\x12\x18\n\x10max_player_count\x18\x04 \x02(\x05\x12\x0f\n\x07version\x18\x05 \x02(\x05\":\n\tOperation\x12\x1f\n\x04type\x18\x01 \x02(\x0e\x32\x11.Sto.Network.Type\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\";\n\rOperationList\x12*\n\noperations\x18\x01 \x03(\x0b\x32\x16.Sto.Network.Operation\"D\n\x0eStoUpdateEntry\x12\x32\n\x0eoperation_list\x18\x01 \x02(\x0b\x32\x1a.Sto.Network.OperationList\"9\n\tStoUpdate\x12,\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1b.Sto.Network.StoUpdateEntry*\x8d\x01\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x17\n\x13REQUEST_SERVER_INFO\x10\x01\x12\x0f\n\x0bSERVER_INFO\x10\x02\x12\x12\n\x0e\x43ONNECT_SERVER\x10\x03\x12\x1b\n\x17\x43ONNECT_SERVER_RESPONSE\x10\x04\x12\x0e\n\nDISCONNECT\x10\x05\x12\r\n\tHEARTBEAT\x10\x06')

_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='Sto.Network.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQUEST_SERVER_INFO', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SERVER_INFO', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECT_SERVER', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECT_SERVER_RESPONSE', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HEARTBEAT', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=586,
  serialized_end=727,
)


UNKNOWN = 0
REQUEST_SERVER_INFO = 1
SERVER_INFO = 2
CONNECT_SERVER = 3
CONNECT_SERVER_RESPONSE = 4
DISCONNECT = 5
HEARTBEAT = 6



_CONNECTSERVER = descriptor.Descriptor(
  name='ConnectServer',
  full_name='Sto.Network.ConnectServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hash', full_name='Sto.Network.ConnectServer.hash', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b''.decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=95,
)


_CONNECTSERVERRESPONSE = descriptor.Descriptor(
  name='ConnectServerResponse',
  full_name='Sto.Network.ConnectServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='success', full_name='Sto.Network.ConnectServerResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='Sto.Network.ConnectServerResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b''.decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_id', full_name='Sto.Network.ConnectServerResponse.client_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=97,
  serialized_end=173,
)


_DISCONNECT = descriptor.Descriptor(
  name='Disconnect',
  full_name='Sto.Network.Disconnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='title', full_name='Sto.Network.Disconnect.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b''.decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='Sto.Network.Disconnect.message', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b''.decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=175,
  serialized_end=219,
)


_SERVERINFO = descriptor.Descriptor(
  name='ServerInfo',
  full_name='Sto.Network.ServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='Sto.Network.ServerInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b''.decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='Sto.Network.ServerInfo.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b''.decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='player_count', full_name='Sto.Network.ServerInfo.player_count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='max_player_count', full_name='Sto.Network.ServerInfo.max_player_count', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='version', full_name='Sto.Network.ServerInfo.version', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=221,
  serialized_end=333,
)


_OPERATION = descriptor.Descriptor(
  name='Operation',
  full_name='Sto.Network.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='Sto.Network.Operation.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='Sto.Network.Operation.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=335,
  serialized_end=393,
)


_OPERATIONLIST = descriptor.Descriptor(
  name='OperationList',
  full_name='Sto.Network.OperationList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='operations', full_name='Sto.Network.OperationList.operations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=395,
  serialized_end=454,
)


_STOUPDATEENTRY = descriptor.Descriptor(
  name='StoUpdateEntry',
  full_name='Sto.Network.StoUpdateEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='operation_list', full_name='Sto.Network.StoUpdateEntry.operation_list', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=456,
  serialized_end=524,
)


_STOUPDATE = descriptor.Descriptor(
  name='StoUpdate',
  full_name='Sto.Network.StoUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entries', full_name='Sto.Network.StoUpdate.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=526,
  serialized_end=583,
)

_OPERATION.fields_by_name['type'].enum_type = _TYPE
_OPERATIONLIST.fields_by_name['operations'].message_type = _OPERATION
_STOUPDATEENTRY.fields_by_name['operation_list'].message_type = _OPERATIONLIST
_STOUPDATE.fields_by_name['entries'].message_type = _STOUPDATEENTRY
DESCRIPTOR.message_types_by_name['ConnectServer'] = _CONNECTSERVER
DESCRIPTOR.message_types_by_name['ConnectServerResponse'] = _CONNECTSERVERRESPONSE
DESCRIPTOR.message_types_by_name['Disconnect'] = _DISCONNECT
DESCRIPTOR.message_types_by_name['ServerInfo'] = _SERVERINFO
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['OperationList'] = _OPERATIONLIST
DESCRIPTOR.message_types_by_name['StoUpdateEntry'] = _STOUPDATEENTRY
DESCRIPTOR.message_types_by_name['StoUpdate'] = _STOUPDATE

class ConnectServer(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _CONNECTSERVER
  
  # @@protoc_insertion_point(class_scope:Sto.Network.ConnectServer)

class ConnectServerResponse(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _CONNECTSERVERRESPONSE
  
  # @@protoc_insertion_point(class_scope:Sto.Network.ConnectServerResponse)

class Disconnect(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _DISCONNECT
  
  # @@protoc_insertion_point(class_scope:Sto.Network.Disconnect)

class ServerInfo(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _SERVERINFO
  
  # @@protoc_insertion_point(class_scope:Sto.Network.ServerInfo)

class Operation(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _OPERATION
  
  # @@protoc_insertion_point(class_scope:Sto.Network.Operation)

class OperationList(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _OPERATIONLIST
  
  # @@protoc_insertion_point(class_scope:Sto.Network.OperationList)

class StoUpdateEntry(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _STOUPDATEENTRY
  
  # @@protoc_insertion_point(class_scope:Sto.Network.StoUpdateEntry)

class StoUpdate(message.Message, metaclass=reflection.GeneratedProtocolMessageType):
  DESCRIPTOR = _STOUPDATE
  
  # @@protoc_insertion_point(class_scope:Sto.Network.StoUpdate)

# @@protoc_insertion_point(module_scope)
